In [3]:
import numpy as np

# Size

Write a function which receives a Numpy array, and returns the number of elements in the numpy array.

You shall not use the size or shape attributes.

# Shape

Write a function which receives a 2D Numpy array, and returns the number of rows and columns in the Numpy array.

# Add

Write a function that receives two 1D Numpy arrays arr1 + arr2 of the same shape.

It returns the sum of both arrays, as if they were summed together.

You may not simply do arr1 + arr2.

# Transpose

Write a function that receives a 2D Numpy array and returns its transposed version.

For instance, the transposed version of

In [5]:
A = np.array([[0,1,2],[3,4,5]])
print(A)

[[0 1 2]
 [3 4 5]]


is

In [6]:
B = np.transpose(A)
print(B)

[[0 3]
 [1 4]
 [2 5]]


Of course, you may not use the transpose() function.

# Median

Write a function that receives a 1D numpy array with integer values.

It returns the median value of this array.

You may not use the median() function.