In [1]:
import numpy as np

# Size

Write a function which receives a Numpy array, and returns the number of elements in the numpy array.

You shall not use the size or shape attributes.

# Shape

Write a function which receives a 2D Numpy array, and returns the number of rows and columns in the Numpy array.

# Add

Write a function that receives two 1D Numpy arrays arr1 and arr2 of the same shape.

It returns the sum of both arrays, as if they were summed together.

You may not simply do arr1 + arr2.

# Transpose

Write a function that receives a 2D Numpy array and returns its transposed version.

For instance, the transposed version of

In [5]:
A = np.array([[0,1,2],[3,4,5]])
print(A)

[[0 1 2]
 [3 4 5]]


is

In [6]:
B = np.transpose(A)
print(B)

[[0 3]
 [1 4]
 [2 5]]


Of course, you may not use the transpose() function.

# Median

Write a function that receives a 1D numpy array with integer values.

It returns the median value of this array.

You may not use the median() function.

# Advanced Max

Write a function that receives a 2D numpy array with integer values, and a parameter dim, with values either 0 or 1.

It returns the max value of this array, but computes it line by line, along the dimension specified (0 means one max value for each of the rows, 1 means one max value for each of the columns).

For instance, the advanced max of 

In [2]:
A = np.array([[0,7,2],[3,4,5]])
print(A)

[[0 1 2]
 [3 4 5]]


Along dimension 0, is

In [5]:
max_array_0 = np.array([7,5])
print(max_array_0)

[7 5]


And along dimension 1, it is

In [6]:
max_array_1 = np.array([3,7,5])
print(max_array_1)

[3 7 5]


In [ ]:
You may not use the max() function from Python or Numpy.