In [18]:
a = [1,2,3,4]
print(id(a))

2899752795136


In [14]:
b = a.copy()
print(b)
print(id(b))
b[0] = 10
print(b)
print(a)

[1, 2, 3, 4]
2899752785152
[10, 2, 3, 4]
[1, 2, 3, 4]


In [19]:
b = a[:]
print(b)
print(id(b))
b[0] = 10
print(b)
print(a)

[1, 2, 3, 4]
2899752921280
[10, 2, 3, 4]
[1, 2, 3, 4]


In [16]:
b = a
print(b)
print(id(b))
b[0] = 10
print(b)
print(a)

[1, 2, 3, 4]
2899752129472
[10, 2, 3, 4]
[10, 2, 3, 4]


In [20]:
def f(my_list):
    my_list[0] = 11
    print(my_list)

In [21]:
a = [1, 2, 3, 4]
print(a)
f(a)
print(a)

[1, 2, 3, 4]
[11, 2, 3, 4]
[11, 2, 3, 4]


In [22]:
a = (1, 2, 3, 4)
print(a)
print(type(a))

(1, 2, 3, 4)
<class 'tuple'>


In [35]:
a = [1, 2, 3, 4]
print(a[:])

[1, 2, 3, 4]


In [37]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [38]:
# How do I get 1245
print(a[:,0:2])

[[1 2]
 [4 5]]
