# Activity 1 - Exam adjustments - solution

For this activity, we will use the numpy library. Let us start by importing it.

In [2]:
import numpy as np

### Problem statement

Let us assume, that I have grades from my students listed in the np.array below. As you can see, the first list contains the column labels (student name, some scores), the second contains the students names and the numpy array has lines, which consist of entries regarding some of the students.

For instance, Chris scored 60 points on the midterm and 80 points on the final exam, leading to an average score of 70 for the whole term.

In [5]:
columns_labels_list = ["MidTerm Score", "FinalExam Score", "Average Score"]
students_list = ["Chris", "Oka", "Norman", "Natalie", "Tony"]
grades_table = np.array([[60, 80, 70], \ # Chris scored 60% on MidTerm, 80% on Finals, Average is 70%
                         [50, 80, 65], \
                         [40, 70, 55], \
                         [60, 70, 65], \
                         [60, 90, 75]])
print(grades_table)

[[60 80 70]
 [50 80 65]
 [40 70 55]
 [60 70 65]
 [60 90 75]]


### Task

Let us assume that, as a professor, I have decided to be lenient towards my students. I realized that the midterm was a bit too difficult compared to last year. To compensate for that, I would like to increase the scores of all students on the midterm by 50%.

Write a **function grade_adjustment()**, which:
- receives a grades table, *grades_table*, as defined above,
- *increases* the scores of all students on the midterm by *50%*,
- *re-calculates* the *average score*, with the new adjusted midterm score,
- and then *returns* the *updated grades table* as its sole output.

**Important note:** The *maximal score* for the midterm exam is *capped* to *100*. This means that a student which score 80 points on the midterm, will not obtain 120 points after the adjustment, but only 100.

### You code below!

In [25]:
from copy import deepcopy

def grade_adjustment(grades_table):
    
    # Initialize a new deepcopy of grades_table
    new_grades_table = deepcopy(grades_table)
    
    for index, line in enumerate(grades_table):
        
        print("---")
        print(index, line)
        # Retrieve the midterm exam score
        # (Do not forget to convert to int/float
        # before any math operations if needed!)
        mid_term_score = line[0]
        
        # Add extra points to midterm!
        # (The score should remain below 100)
        mid_term_score_adjusted = 1.5*mid_term_score
        if(mid_term_score_adjusted > 100):
            mid_term_score_adjusted = 100
        
        # Add new midterm score to table
        # (Do not forget to convert it back to a string before
        # reassigning to numpy array!)
        new_grades_table[index, 0] = mid_term_score_adjusted
        
        # Retrieve the final exam score
        # (Do not forget to convert to int/float before any math operations!)
        final_score = line[1]
        
        # Compute the mean of both the final exam score and the adjusted midterm score
        new_mean = (final_score + mid_term_score_adjusted)/2
        
        # Add new mean to grades table.
        # (Do not forget to convert to string!)
        new_grades_table[index, 2] = new_mean
            
    return new_grades_table

In [11]:
from copy import deepcopy

def grade_adjustment(grades_table):
    
    # Initialize a new deepcopy of grades_table
    new_grades_table = deepcopy(grades_table)
    
    for index, line in enumerate(grades_table):
        
        print("---")
        print(index, line)
        # Retrieve the midterm exam score
        # (Do not forget to convert to int/float
        # before any math operations if needed!)
        mid_term_score = line[0]
        
        # Add extra points to midterm!
        # (The score should remain below 100)
        mid_term_score_adjusted = min(100, 1.5*mid_term_score)
        
        # Add new midterm score to table
        # (Do not forget to convert it back to a string before
        # reassigning to numpy array!)
        new_grades_table[index, 0] = mid_term_score_adjusted
        
        # Retrieve the final exam score
        # (Do not forget to convert to int/float before any math operations!)
        final_score = line[1]
        
        # Compute the mean of both the final exam score and the adjusted midterm score
        new_mean = (final_score + mid_term_score_adjusted)/2
        
        # Add new mean to grades table.
        # (Do not forget to convert to string!)
        new_grades_table[index, 2] = new_mean
            
    return new_grades_table

### Expected results

In [26]:
grades_table = np.array([[60, 80, 70], \
                         [50, 80, 65], \
                         [40, 70, 55], \
                         [60, 70, 65], \
                         [60, 90, 75]])

# This should print
"""
[[90 80 85]
 [75 80 77]
 [60 70 65]
 [90 70 80]
 [90 90 90]]
"""
new_grades = grade_adjustment(grades_table)
print(new_grades)

---
0 [60 80 70]
---
1 [50 80 65]
---
2 [40 70 55]
---
3 [60 70 65]
---
4 [60 90 75]
[[90 80 85]
 [75 80 77]
 [60 70 65]
 [90 70 80]
 [90 90 90]]


In [27]:
grades_table = np.array([[60, 80, 70], \
                         [50, 80, 65], \
                         [80, 70, 75], \
                         [90, 70, 80], \
                         [60, 90, 75]])

# This should print
"""
[[ 90  80  85]
 [ 75  80  77]
 [100  70  85]
 [100  70  85]
 [ 90  90  90]]
"""
new_grades = grade_adjustment(grades_table)
print(new_grades)

---
0 [60 80 70]
---
1 [50 80 65]
---
2 [80 70 75]
---
3 [90 70 80]
---
4 [60 90 75]
[[ 90  80  85]
 [ 75  80  77]
 [100  70  85]
 [100  70  85]
 [ 90  90  90]]
