In [5]:
import numpy as np
my_list = np.array([[1, 2, 3], [5, 7, 11]])
print(my_list)
for index, line in enumerate(my_list):
    print(index, line)

[[ 1  2  3]
 [ 5  7 11]]
0 [1 2 3]
1 [ 5  7 11]


In [7]:
my_list = np.array([[1, 2, 3], [5, 7, 11]])
print(my_list[:, 0:2])

[[1 2]
 [5 7]]


In [8]:
grades_table = np.array([["Student Name", "MidTerm Score", "FinalExam Score", "Average Score"], \
                         ["Chris", '60', '80', '70'], \
                         ["Oka", '50', '80', '65'], \
                         ["Norman", '40', '70', '55'], \
                         ["Natalie", '60', '70', '65'], \
                         ["Tony", '60', '90', '75']])

In [10]:
print(grades_table[1:, :])

[['Chris' '60' '80' '70']
 ['Oka' '50' '80' '65']
 ['Norman' '40' '70' '55']
 ['Natalie' '60' '70' '65']
 ['Tony' '60' '90' '75']]
