In [2]:
import numpy as np

In [2]:
array1 = np.array([0, 2, 1, 4])
print(array1)

[0 2 1 4]


In [3]:
print(array1)
print(type(array1))
array1_as_list = list(array1)
print(array1_as_list)
print(type(array1_as_list))

[0 2 1 4]
<class 'numpy.ndarray'>
[0, 2, 1, 4]
<class 'list'>


In [4]:
array1 = np.array([0, 2, 1, 4])
print(len(array1))
print(array1.shape)
print(array1.size)

4
(4,)
4


In [5]:
two_d_array = np.array([[1,2],[3,4]])
print(two_d_array)
print(len(two_d_array))
print(two_d_array.shape)
print(two_d_array.size)

[[1 2]
 [3 4]]
2
(2, 2)
4


In [6]:
array1 = np.array([0, 2, 1, 4])
print(array1)
print(array1[0])
print(array1[1])

[0 2 1 4]
0
2


In [7]:
two_d_array = np.array([[1,2],[3,4]])
print(two_d_array)
print(two_d_array[0])
print(two_d_array[0][1])

[[1 2]
 [3 4]]
[1 2]
2


In [8]:
print(two_d_array[0,1])
print(two_d_array[:,1])
print(two_d_array[0,:])

2
[2 4]
[1 2]


In [9]:
array1 = np.array([0, 2, 1, 4])
print(array1)
for element in array1:
    print(element)

[0 2 1 4]
0
2
1
4


In [10]:
array2 = np.array([1, 2, 3, 5])
print(array2)
print(array1)

[1 2 3 5]
[0 2 1 4]


In [11]:
array1 = np.array([0, 2, 1, 4])
array2 = np.array([1, 2, 3, 5])
print(array1)
print(array2)
sum_array = array1 + array2
print(sum_array)

[0 2 1 4]
[1 2 3 5]
[1 4 4 9]


In [12]:
array1 = np.array([0, 2, 1, 4])
number = 7
print(array1)
sum_array = array1 + number
print(sum_array)

[0 2 1 4]
[ 7  9  8 11]


In [13]:
print(array1)
print(array2)
conc_array = np.concatenate([array1, array2])
print(conc_array)

[0 2 1 4]
[1 2 3 5]
[0 2 1 4 1 2 3 5]


In [14]:
array1 = np.array([0, 2, 1, 4])
array2 = np.array([1, 2, 3, 5])
print(array1)
print(array2)
mult_arrays = array1*array2
print(mult_arrays)

[0 2 1 4]
[1 2 3 5]
[ 0  4  3 20]


In [15]:
n = 4
mult_array_int = array1*n
print(mult_array_int)

[ 0  8  4 16]


In [16]:
two_d_array1 = np.array([[1,2],[3,4]])
two_d_array2 = two_d_array1
print(two_d_array1)
print(two_d_array2)
print(id(two_d_array1))
print(id(two_d_array2))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
2711337376784
2711337376784


In [17]:
two_d_array1[0][0] = 17
print(two_d_array1)
print(two_d_array2)

[[17  2]
 [ 3  4]]
[[17  2]
 [ 3  4]]


In [18]:
array1 = np.array([0, 2, 1, 4, 7])
print(array1)
min_val = np.min(array1)
print(min_val)
argmin_val = np.argmin(array1)
print(argmin_val)
max_val = np.max(array1)
print(max_val)
argmax_val = np.argmax(array1)
print(argmax_val)
mean_val = np.mean(array1)
print(mean_val)
median_val = np.median(array1)
print(median_val)
summed_val = np.sum(array1)
print(summed_val)

[0 2 1 4 7]
0
0
7
4
2.8
2.0
14


In [19]:
print(np.cos(0))
print(np.sin(0))
print(np.pi)
print(np.log(1))
print(np.exp(0))

1.0
0.0
3.141592653589793
0.0
1.0


In [20]:
# Numpy.random.choice() mimics a dice roll
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)
dice_roll = np.random.choice([1, 2, 3, 4, 5, 6])
print(dice_roll)

5
6
5
4
2
5
